run:
  # Timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  # Set Go version to match CI environment
  go: '1.23'
  # Examine test files as well
  tests: true
  # Skip all issues from typecheck linter
  allow-parallel-runners: true
  skip-files:
    - ".*_test.go$"
    - ".*/mocks/.*"

# Linter settings
linters-settings:
  typecheck:
    # Force disable typecheck linter completely
    disabled: true

# Available linters
linters:
  disable-all: true
  enable:
    - gofmt
    - govet
  disable:
    - typecheck  # Explicitly disable typecheck to avoid issues with mocks and standard library 