version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: .

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - examples/**/*
      - pkg/**/*
      - cmd/**/*
      - go.mod
      - go.sum

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: pontus-devoteam
    name: agent-sdk-go
  draft: false
  prerelease: auto
  footer: |
    ## Docker images
    {{ range $asset := .FilteredAssets }}
    - `{{ $asset.Name }}` ({{ $asset.Size }})
    {{- end }}

    Docker images can be found at [pontus-devoteam/agent-sdk-go](https://hub.docker.com/r/pontus-devoteam/agent-sdk-go). 